# Generated by Django 2.2 on 2019-05-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='bill',
        ),
    ]
